compute_logs:
  module: dagster_aws.s3.compute_log_manager
  class: S3ComputeLogManager
  config:
    bucket:
      env: S3_BUCKET
    endpoint_url:
      env: S3_ENDPOINT

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

run_launcher:
  module: dagster_docker
  class: DockerRunLauncher
  config:
    env_vars:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DAGSTER_DATABASE
      - FEAST_DATABASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - S3_BUCKET
      - S3_ENDPOINT
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
    image:
      env: DOCKER_IMAGE
    network:
      env: DOCKER_NETWORK
    container_kwargs:
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

run_storage:
  module: dagster_postgres.run_storage
  class: PostgresRunStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      port:
        env: POSTGRES_PORT
      db_name:
        env: DAGSTER_DATABASE

schedule_storage:
  module: dagster_postgres.schedule_storage
  class: PostgresScheduleStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      port:
        env: POSTGRES_PORT
      db_name:
        env: DAGSTER_DATABASE

event_log_storage:
  module: dagster_postgres.event_log
  class: PostgresEventLogStorage
  config:
    postgres_db:
      hostname:
        env: POSTGRES_HOST
      username:
        env: POSTGRES_USER
      password:
        env: POSTGRES_PASSWORD
      port:
        env: POSTGRES_PORT
      db_name:
        env: DAGSTER_DATABASE

sensors:
  use_threads: true
  num_workers: 8

schedules:
  use_threads: true
  num_workers: 8

auto_materialize:
  enabled: true
