services:
  traefik:
    image: traefik:v2.10
    command:
      - --api.insecure=true
      - --providers.kubernetesingress=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.tls=true
    labels:
      kompose.serviceaccount-name: traefik-account
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host

  timescaledb:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?Variable POSTGRES_PASSWORD not set}
      POSTGRES_USER: ${POSTGRES_USER?Variable POSTGRES_USER not set}
    volumes:
      - timescaledb_data:/var/lib/postgresql/data

volumes:
  timescaledb_data:
