name: "CI"
on:
  pull_request:

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # - name: Build and push
      #   uses: docker/bake-action@v3
      #   with:
      #     files: |
      #       stacks/docker-compose.yml
  # Until a release is made larger than 1.28, we need to build kompose from source
  build-kompose:
    runs-on: ubuntu-22.04
    name: Build kompose
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ^1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          repository: kubernetes/kompose

      - name: Build
        run: make bin

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "kompose"
          path: "kompose"
  e2e-tests:
    runs-on: ubuntu-22.04
    name: E2E Tests
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Install kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.28.0/kompose-linux-amd64 -o /usr/local/bin/kompose
          chmod +x /usr/local/bin/kompose
      - name: Install k8s cluster
        run: kind create cluster --config config/kind/config.yml
      - name: Deploy stack
        run: |
          kompose convert -f stacks/docker-compose.yml -o manifest/k8s.yml
          kubectl apply -f manifest
      - name: Run tests
        run: poetry run pytest -m e2e
  integration-tests:
    runs-on: ubuntu-22.04
    name: Integration Tests
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Install kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.28.0/kompose-linux-amd64 -o /usr/local/bin/kompose
          chmod +x /usr/local/bin/kompose
      - name: Install k8s cluster
        run: kind create cluster --config config/kind/config.yml
      - name: Deploy stack
        run: |
          kompose convert -f stacks/docker-compose.yml -o manifest/k8s.yml
          kubectl apply -f manifest
      - name: Run tests
        run: poetry run pytest -m integration
  unit-tests:
    runs-on: ubuntu-22.04
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -m unit
