name: "CI"
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
