name: "CI"
on:
  pull_request:

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/bake-action@v3
        with:
          files: |
            stacks/docker-compose.yml
  e2e-tests:
    runs-on: ubuntu-22.04
    name: E2E Tests
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Install kompose
        run: |
          curl -L https://github.com/kubernetes/kompose/releases/download/v1.28.0/kompose-linux-amd64 -o /usr/local/bin/kompose
          chmod +x /usr/local/bin/kompose
      - name: Install k8s cluster
        run: kind create cluster
      - name: Deploy stack
        run: |
          kompose convert -f stacks/docker-compose.yml -o stacks/k8s.yml
          kubectl apply -f stacks/k8s.yml
      - name: Run tests
        run: poetry run pytest -m e2e
  integration-tests:
    runs-on: ubuntu-22.04
    name: Integration Tests
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -m integration
  unit-tests:
    runs-on: ubuntu-22.04
    name: Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Install python dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -m unit
