name: "CI"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install python dependencies
        run: poetry install
      - name: Unit Tests
        run: ./scripts/test.sh -m unit
      # - name: Build images
      #   run: ./scripts/build.sh
      # - name: Deploy stack
      #   run: ./scripts/deploy.sh
      - name: Integration Tests
        run: ./scripts/test.sh -m integration
      - name: End-to-End Tests
        run: ./scripts/test.sh -m e2e
